// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlVSROzgCZWdY-LCYmYHXdxriQnkFqkI',
    appId: '1:924303074294:android:cf5c6570cc8807b6ed1dd7',
    messagingSenderId: '924303074294',
    projectId: 'hankookji-namgu',
    storageBucket: 'hankookji-namgu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsLuCIADn22vOapWhXWVMGmYJFn6RCl4',
    appId: '1:924303074294:ios:4d44e122d75fd2d2ed1dd7',
    messagingSenderId: '924303074294',
    projectId: 'hankookji-namgu',
    storageBucket: 'hankookji-namgu.firebasestorage.app',
    iosBundleId: 'com.doyakmin.hangookji.namgu',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFMQyRp5uI5mH04xvmMVLiX8FCRApZm0',
    appId: '1:924303074294:web:954fac8b1cdd5fe8ed1dd7',
    messagingSenderId: '924303074294',
    projectId: 'hankookji-namgu',
    authDomain: 'hankookji-namgu.firebaseapp.com',
    storageBucket: 'hankookji-namgu.firebasestorage.app',
    measurementId: 'G-9P2F9JQ03C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsLuCIADn22vOapWhXWVMGmYJFn6RCl4',
    appId: '1:924303074294:ios:45c7d616c24311b5ed1dd7',
    messagingSenderId: '924303074294',
    projectId: 'hankookji-namgu',
    storageBucket: 'hankookji-namgu.firebasestorage.app',
    iosBundleId: 'com.doyakmin.hangookji.namgu.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRFMQyRp5uI5mH04xvmMVLiX8FCRApZm0',
    appId: '1:924303074294:web:41ec5d2940314b6aed1dd7',
    messagingSenderId: '924303074294',
    projectId: 'hankookji-namgu',
    authDomain: 'hankookji-namgu.firebaseapp.com',
    storageBucket: 'hankookji-namgu.firebasestorage.app',
    measurementId: 'G-RV04FLCH71',
  );

}